# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fea9938ce4f562a9e670061948b8ef7769f7dd85cd82a451c58aa1f617ef6a2b8ca803233ae6292d56d4c72f6a23a70dde49aab6c003709507bae5008b5b7dd0
  strava_client_id: 11442
  strava_api_key: 7223e5b37714ed5c7d1d953924a2e5a9423a8dee
  strava_api_secret: 5445beb6368bee9e23f0ab74a7e22144f6dc7221
test:
  secret_key_base: bb6047f96f4fba6abfe675004070b7869945036524e2595206c5eccfcf0848f70ddf1530984d28b3e8768e7a00aa973247872339f64d98a5a41de1173f97444e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
